// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTC6eZIJ1IYFvgvO-G8KriuEdkfJ9LCiY',
    appId: '1:348321573488:web:97831848b84ea52194a2b5',
    messagingSenderId: '348321573488',
    projectId: 'croussgo',
    authDomain: 'croussgo.firebaseapp.com',
    storageBucket: 'croussgo.appspot.com',
    measurementId: 'G-4STVKVZV3C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbDMKE3JQCPT7RQ6knEYHVZARZr_w-mS4',
    appId: '1:348321573488:android:7c0b9a7f977d817894a2b5',
    messagingSenderId: '348321573488',
    projectId: 'croussgo',
    storageBucket: 'croussgo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAd3rI0-uc1qGHNbpVBnh6rhjc3-e2uDl0',
    appId: '1:348321573488:ios:c4233919d78ab7a994a2b5',
    messagingSenderId: '348321573488',
    projectId: 'croussgo',
    storageBucket: 'croussgo.appspot.com',
    iosClientId: '348321573488-371m5j13nedt1icg41livobon86phf29.apps.googleusercontent.com',
    iosBundleId: 'com.imt.fw.crousgo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAd3rI0-uc1qGHNbpVBnh6rhjc3-e2uDl0',
    appId: '1:348321573488:ios:1eba753616bcb89194a2b5',
    messagingSenderId: '348321573488',
    projectId: 'croussgo',
    storageBucket: 'croussgo.appspot.com',
    iosClientId: '348321573488-ibedrne13ki86ouucok18kqq15ri9jr5.apps.googleusercontent.com',
    iosBundleId: 'com.imt.fw.crousgo.RunnerTests',
  );
}
